DELIMITER $$

CREATE PROCEDURE sp_store_products(codigo VARCHAR(32), nombre VARCHAR(128), equipo VARCHAR(20), contador VARCHAR(20), localizacion VARCHAR(20), tamanho_de_localizacion VARCHAR(50), otra_localizacion VARCHAR(5), cantidad INT, marca_harfon BOOLEAN, marca_wps BOOLEAN, marca_tras BOOLEAN, marca_zen BOOLEAN, marca_blanca BOOLEAN, marca_otro BOOLEAN, tipo_de_empaque VARCHAR(50), condicion_del_paquete VARCHAR(10), condicion_del_producto VARCHAR(10), tipo_de_paquete_grupo1 VARCHAR(50), cantidad_de_paquete_grupo1 INT, cantidad_de_producto_grupo1 INT, tipo_de_paquete_grupo2 VARCHAR(50), cantidad_de_paquete_grupo2 INT, cantidad_de_producto_grupo2 INT, tipo_de_paquete_grupo3 VARCHAR(50), cantidad_de_paquete_grupo3 INT, cantidad_de_producto_grupo3 INT, tipo_de_paquete_grupo4 VARCHAR(50), cantidad_de_paquete_grupo4 INT, cantidad_de_producto_grupo4 INT, preguntar_inspeccion VARCHAR(5), no_encontrado BOOLEAN, cuarentena VARCHAR(5), comentarios TEXT, auditoria BOOLEAN, agente_de_usuario VARCHAR(255), direccion_remota VARCHAR(255))

    BEGIN

        INSERT INTO inv_listados (code, name, team, count, location, location_size, location_others, quantity, brand_harfon, brand_wps, brand_tras, brand_zen, brand_blank, brand_other, package_type, pack_condition, product_condition, package_type_group1, package_quantity_group1, prod_quantity_group1, package_type_group2, package_quantity_group2, prod_quantity_group2, package_type_group3, package_quantity_group3, prod_quantity_group3, package_type_group4, package_quantity_group4, prod_quantity_group4, ask_inspection, not_found, quarantine, comments, audit, http_user_agent, remote_addr, created_at) VALUES (codigo, nombre, equipo, contador, localizacion, tamanho_de_localizacion, otra_localizacion, cantidad, marca_harfon, marca_wps, marca_tras, marca_zen, marca_blanca, marca_otro, tipo_de_empaque, condicion_del_paquete, condicion_del_producto, tipo_de_paquete_grupo1, cantidad_de_paquete_grupo1, cantidad_de_producto_grupo1, tipo_de_paquete_grupo2, cantidad_de_paquete_grupo2, cantidad_de_producto_grupo2, tipo_de_paquete_grupo3, cantidad_de_paquete_grupo3, cantidad_de_producto_grupo3, tipo_de_paquete_grupo4, cantidad_de_paquete_grupo4, cantidad_de_producto_grupo4, preguntar_inspeccion, no_encontrado, cuarentena, comentarios, auditoria, agente_de_usuario, direccion_remota, NOW());

    END;$$
    
DELIMITER ;
